name: Run C# Script Manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # 案1
    #- name: Run Script
    #  working-directory: ./src
    #  run: dotnet run
  
    # 案2
    - name: Run Sctipt2
      run: |
        cd src
        dotnet run
